# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

NOW=`date +%Y-%m-%d.%H%M%S`
LFILE=/var/log/user-audit/$USER-$HOST-$NOW.log

alias exit="exit && exit"
